program: autoencoder.py
method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  embedding_size:
    values: [8, 16, 32]
  lr:
    values: [0.0001, 0.0005, 0.001]
  noise_std:
    values: [0.0, 0.05, 0.1, 0.2]
  channel_mask_prob:
    values: [0.0, 0.1, 0.15, 0.25]
