program: autoencoder.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  embedding_size:
    values: [32]
  lr:
    values: [0.001]
  noise_std:
    values: [0.0, 0.1, 0.2]
  channel_mask_prob:
    values: [0.0, 0.15, 0.25]
